/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula09exe02;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author unifgimoreira
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        cc1 = new javax.swing.JColorChooser();
        btnPequeno = new javax.swing.JButton();
        btnGrande = new javax.swing.JButton();
        btnMedio = new javax.swing.JButton();
        btnTexto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jp1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jp1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        btnPequeno.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnPequeno.setText("PEQUENO");
        btnPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPequenoActionPerformed(evt);
            }
        });

        btnGrande.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnGrande.setText("GRANDE");
        btnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrandeActionPerformed(evt);
            }
        });

        btnMedio.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnMedio.setText("MÉDIO");
        btnMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioActionPerformed(evt);
            }
        });

        btnTexto.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnTexto.setText("TEXTO");
        btnTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnPequeno)
                        .addGap(33, 33, 33)
                        .addComponent(btnMedio)
                        .addGap(31, 31, 31)
                        .addComponent(btnGrande)
                        .addGap(31, 31, 31)
                        .addComponent(btnTexto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jp1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MouseDragged
        Graphics g = getGraphics();
        Color c = cc1.getColor();
        g.setColor(c);
        g.fillOval(evt.getX() + 12, evt.getY() + 30, tamanhoPincel, tamanhoPincel);
    }//GEN-LAST:event_jp1MouseDragged

    private void btnPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPequenoActionPerformed
        tamanhoPincel = 5;
    }//GEN-LAST:event_btnPequenoActionPerformed

    private void btnMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioActionPerformed
        tamanhoPincel = 15;
    }//GEN-LAST:event_btnMedioActionPerformed

    private void btnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrandeActionPerformed
        tamanhoPincel = 30;
    }//GEN-LAST:event_btnGrandeActionPerformed

    private void btnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextoActionPerformed
        Graphics g = getGraphics();
        Color c = cc1.getColor();
        g.setColor(c);
        String texto = JOptionPane.showInputDialog("Digite seu texto: ");
        g.drawString(texto, 150, 150);
    }//GEN-LAST:event_btnTextoActionPerformed
    
    private int tamanhoPincel = 15;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrande;
    private javax.swing.JButton btnMedio;
    private javax.swing.JButton btnPequeno;
    private javax.swing.JButton btnTexto;
    private javax.swing.JColorChooser cc1;
    private javax.swing.JPanel jp1;
    // End of variables declaration//GEN-END:variables
}
